export const services = [
  { id: 'oil-filtration-machines', number: '01', title: 'Industrial Oil Filtration Machines', short: 'Oil Filtration', icon: '⚙️', tagline: 'High-performance systems for continuous industrial use', description: 'Available in portable, inline, and offline configurations. Handles lubricants, hydraulic oils, and coolants with ISO-certified filtration media.', features: ['Portable, inline & offline configs', 'ISO-certified filtration media', 'Real-time contamination indicators', 'Continuous duty rated', 'Up to 200 LPM flow rate'], specs: { 'Flow Rate': 'Up to 200 LPM', 'Filtration': 'Down to 1 micron', 'Pressure': 'Up to 25 bar', 'Temperature': 'Up to 120°C' }, result: '99% filtration efficiency', color: '#2563EB' },
  { id: 'fine-filtration-services', number: '02', title: 'Fine Filtration Services', short: 'Fine Filtration', icon: '🔬', tagline: 'Micron-level restoration to OEM specifications', description: 'On-site or facility-based micron filtration that restores contaminated lubricants to manufacturer specifications.', features: ['Down to 0.5 micron', 'On-site or facility-based', 'Oil analysis reporting', 'OEM spec restoration', 'Scheduled service contracts'], specs: { 'Filtration': 'Down to 0.5 micron', 'Turnaround': '24–48 hours', 'Capacity': 'Up to 10,000L/day', 'Reporting': 'ISO 4406 cleanliness' }, result: '3–5× oil life extension', color: '#7C3AED' },
  { id: 'hydraulic-oil-purification', number: '03', title: 'Hydraulic Oil Purification', short: 'Hydraulic Oil', icon: '💧', tagline: 'Dewatering & particle removal for hydraulic systems', description: 'Specialized systems maintaining ISO cleanliness codes and preventing pump and valve failures from contamination.', features: ['Achieves ISO 16/14/11', 'Water content < 50 ppm', 'Prevents pump & valve failure', 'Dewatering & degassing', 'Real-time NAS monitoring'], specs: { 'Cleanliness': 'ISO 16/14/11', 'Water': '< 50 ppm', 'Particles': '< 100/ml @ 4µm', 'Flow': 'Up to 150 LPM' }, result: '68% reduction in pump failures', color: '#0891B2' },
  { id: 'coolant-management', number: '04', title: 'Coolant Management Systems', short: 'Coolant Mgmt', icon: '🌡️', tagline: 'Centralized coolant filtration & recycling', description: 'Centralized systems for CNC machining centers and transfer lines. Reduces coolant consumption while maintaining cutting performance.', features: ['Up to 70% coolant savings', 'CNC & transfer line ready', 'Tramp oil separation', 'pH & concentration control', 'Bacterial growth prevention'], specs: { 'Savings': 'Up to 70%', 'Capacity': 'Up to 50,000L', 'Machines': 'Up to 200 CNC', 'Monitoring': 'Real-time pH & Brix' }, result: '70% coolant cost reduction', color: '#10B981' },
  { id: 'oil-condition-monitoring', number: '05', title: 'Oil Condition Monitoring', short: 'Oil Monitoring', icon: '📊', tagline: 'Real-time sensor-based contamination tracking', description: 'IoT-enabled monitoring of oil cleanliness, viscosity, and contamination. Enables predictive maintenance and data-driven schedules.', features: ['Real-time particle counting', 'WiFi / 4G / RS485 connectivity', 'SMS & email alerts', 'Cloud dashboard access', 'Historical trending reports'], specs: { 'Sensors': 'Particle, water, viscosity', 'Connectivity': 'WiFi / 4G / RS485', 'Alerts': 'SMS & email', 'Accuracy': '± 2% NAS class' }, result: 'Predict failures 2 weeks early', color: '#F59E0B' },
  { id: 'turnkey-integration', number: '06', title: 'Turnkey Plant Integration', short: 'Turnkey', icon: '🏭', tagline: 'Complete design, supply, install & commission', description: 'End-to-end project delivery for new or existing plants. Backed by 24/7 AMC and field service support.', features: ['End-to-end project delivery', 'New & existing plant support', 'Operator training included', 'Annual maintenance contracts', '24/7 field service'], specs: { 'Timeline': '4–12 weeks', 'Warranty': '2 years', 'AMC': 'Available', 'Support': '24/7 field service' }, result: 'ROI within 6 months', color: '#EF4444' },
]

export const industries = [
  { id: 'automobile', icon: '🏭', title: 'Automobile Manufacturing', sub: 'OEM · Tier 1 · Tier 2', desc: 'Hydraulic press lines, engine assembly, and transmission testing — our systems keep your production at peak ISO cleanliness.' },
  { id: 'steel-metals', icon: '⚙️', title: 'Steel & Metals', sub: 'Rolling Mills · Forging Plants', desc: 'Rolling oil purification and bearing lube systems for the most demanding metal forming environments.' },
  { id: 'power-generation', icon: '🔌', title: 'Power Generation', sub: 'Turbine Lube Oil Systems', desc: 'Turbine oil dewatering and transformer oil filtration for continuous power generation reliability.' },
  { id: 'cement-mining', icon: '🏗️', title: 'Cement & Mining', sub: 'Heavy Equipment Hydraulics', desc: 'Heavy equipment hydraulic systems and crusher lube circuits built for the harshest environments.' },
  { id: 'rubber-plastics', icon: '🧪', title: 'Rubber & Plastics', sub: 'Press Hydraulics · Coolants', desc: 'Injection moulding hydraulics and extruder lube systems for precision plastic manufacturing.' },
  { id: 'oil-petrochemical', icon: '🛢️', title: 'Oil & Petrochemical', sub: 'Process Oils · Transformer Oil', desc: 'Process oil conditioning and transformer oil purification for oil & gas infrastructure.' },
]

export const caseStudies = [
  { id: 'chennai-automobile-oem', tag: 'Automobile OEM', location: 'Chennai, Tamil Nadu', title: 'Hydraulic System Overhaul for Engine Assembly Line', problem: 'Chronic hydraulic pump failures causing 12+ hours of unplanned downtime per month, costing ₹8–10 lakhs monthly in lost production across a 24-pump hydraulic circuit.', solution: 'Hydroclean installed inline fine filtration units achieving ISO 16/14/11 cleanliness. A 3-month phased installation with zero production stoppage.', results: ['68% reduction in unplanned downtime', '₹28 lakhs in annual savings', '3× pump life extension', 'ISO 16/14/11 cleanliness achieved'], metrics: [{ value: '68%', label: 'Downtime Reduction' }, { value: '₹28L', label: 'Annual Savings' }, { value: '3×', label: 'Pump Life' }], industry: 'automobile' },
  { id: 'pune-steel-rolling', tag: 'Steel Rolling Mill', location: 'Pune, Maharashtra', title: 'Lube Oil Purification for Cold Rolling Mill', problem: 'Contaminated rolling oil was shortening roll bearing life from 8 months to under 3 months, causing frequent unscheduled stops and high lubricant disposal costs.', solution: 'Deployed centralized fine filtration + dewatering system maintaining NAS Class 6 cleanliness continuously. Integrated with plant SCADA for monitoring.', results: ['3× oil life extension', '60% bearing cost reduction', '₹15 lakhs annual savings', 'NAS Class 6 maintained 24/7'], metrics: [{ value: '3×', label: 'Oil Life' }, { value: '60%', label: 'Bearing Cost Cut' }, { value: '₹15L', label: 'Annual Savings' }], industry: 'steel-metals' },
  { id: 'gujarat-power-plant', tag: 'Power Generation', location: 'Gujarat', title: 'Turbine Lube Oil Conditioning System', problem: 'Water ingress and particulate contamination in a 12,000-litre turbine oil reservoir was causing accelerated bearing wear and risking turbine failure.', solution: "Hydroclean's high-flow dewatering and filtration unit restored the full reservoir in 48 hours and now maintains continuous cleanliness online.", results: ['100% oil restored vs. replacement', 'Water content < 50 ppm achieved', '₹42 lakhs oil replacement avoided', 'Continuous online conditioning'], metrics: [{ value: '100%', label: 'Oil Restored' }, { value: '<50ppm', label: 'Water Content' }, { value: '₹42L', label: 'Cost Avoided' }], industry: 'power-generation' },
]

export const stats = [
  { value: 40, suffix: '%', label: 'Average Oil Cost Reduction', icon: '📉' },
  { value: 25, suffix: '%', label: 'Fewer Unplanned Stoppages', icon: '⏱️' },
  { value: 1, suffix: ' μm', label: 'Absolute Filtration Precision', icon: '🔬' },
  { value: 18, suffix: '+', label: 'Years of Industrial Expertise', icon: '🏆' },
]

export const clients = ['Tata Motors', 'Mahindra', 'Ashok Leyland', 'TVS Group', 'JSW Steel', 'Ultratech', 'BHEL', 'L&T']

export const problems = [
  { icon: '🔧', title: 'Frequent Machine Failures', desc: 'Contaminated oil is the #1 cause of hydraulic pump and valve failure. Every breakdown costs hours of lost production.' },
  { icon: '💸', title: 'Skyrocketing Oil Costs', desc: 'Premature oil disposal due to contamination drains your maintenance budget — often unnecessarily.' },
  { icon: '⏸️', title: 'Unplanned Downtime', desc: 'Your production line stops. Engineers scramble. Orders get delayed. Contaminated oil triggers 70% of hydraulic failures.' },
  { icon: '📋', title: 'Failed Compliance Checks', desc: 'ISO cleanliness requirements are non-negotiable for OEM warranties and quality certifications.' },
]

export const processSteps = [
  { step: '01', title: 'Free Site Assessment', desc: 'Our engineers visit your plant, analyze oil types, contamination levels, and operational requirements at no cost.' },
  { step: '02', title: 'Custom Solution Design', desc: 'We specify the optimal filtration system, media grade, and configuration for your exact machinery and oil types.' },
  { step: '03', title: 'Manufacturing & QC', desc: 'Systems built to order at our facility. Every unit quality-tested to ISO standards before dispatch.' },
  { step: '04', title: 'Installation & Training', desc: 'Certified technicians handle complete installation, commissioning, and comprehensive operator training.' },
  { step: '05', title: 'Monitoring & AMC', desc: 'Ongoing performance monitoring, periodic servicing, and annual maintenance contracts keep your systems optimal.' },
]
